import { eudox } from "@/libs/fonts";
import "@/styles/global.css";
import type { Metadata } from "next";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import createClient from "@/db/client";
import MobileMenu from "@/components/MobileMenu";
import { Analytics } from '@vercel/analytics/react';

export const metadata: Metadata = {
  title: "Lalasia",
  description: "Generated by create next app",
};

export const revalidate = 0;
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  return (
    <html lang="en">
      <body className={eudox.className}>
        <Header user={user} />
        {children}
        <Footer />
        <MobileMenu />
        <ToastContainer />
      </body>
      <Analytics />
    </html>
  );
}
